export const USER_ACTION_TYPES = {
  GET_USER_INFO: "GET_USER_INFO",
};

export const MOVIES_ACTION_TYPES = {
  GET_MOVIES_LIST: "GET_MOVIES",
  ADD_MOVIES: "ADD_MOVIE",
  GET_MOVIE: "GET_MOVIE",
  CHANGE_MOVIE: "CHANGE_MOVIE",
  PARTIAL_CHANGE_MOVIE: "PARTIAL_CHANGE_MOVIE",
  DELETE_MOVIE: "DELETE_MOVIE",
  SET_PAGE: "SET_PAGE",
};

export const LOADER_ACTION_TYPES = {
  SET_STATUS_LOADER: "SET_STATUS_LOADER",
};
